services:
  back:
    container_name: workshop-back
    image: workshop-organizer
    build:
      context: ./${JAVA_DIR}
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10

  front:
    container_name: workshop-front
    image: workshop-front
    build:
      context: ./${ANGULAR_DIR}
    ports:
      - "80:80"
    depends_on:
      back:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
