name: Build Test Frontend

on: [workflow_call]

jobs:
  build-test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code # Récupère le code du repo
        uses: actions/checkout@v4
      - name: Load shared path config
        run: ./scripts/load-path-env.sh
      - name: Set up Docker Buildx # Prépare l'outil Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry # Authentification au registre GitHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CI-ACTION-TOKEN }}
      - name: Build and run frontend tests (docker-compose) # Build et test frontend via docker-compose
        run: |
          docker compose -f "$ANGULAR_DIR/docker-compose.yml" up --build --abort-on-container-exit --exit-code-from tests || docker compose -f "$ANGULAR_DIR/docker-compose.yml" logs
      - name: Upload frontend test results # Sauvegarde les résultats de test frontend
        uses: actions/upload-artifact@v4
        with:
          name: test-results-frontend
          path: ${{ env.ANGULAR_DIR }}/reports/*.xml
      - name: Upload coverage report (Angular) # Sauvegarde le rapport de couverture Angular
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-angular
          path: ${{ env.ANGULAR_DIR }}/coverage/
